general:
  library_path: ''
  daemon_mode: 'foreground'
  schedule_time_key: 'minutes'
  schedule_time_value: 30
  log_level: 'info'
  config_version: '1.0.0'

filters:
  minimum_year: '1960'
  minimum_runtime_mins: '60'
  minimum_rating: '7.0'
  minimum_votes: 5000
  minimum_seeders: 1
  genre_minimum_rating_dict: {
  }
  good_country_list: [
  ]
  # description: permitted imdb language list comma separated list
  # type: list
  # value: n/a
  # example: 'en', 'fr',
  good_language_list: [
  ]
  # description: bad index title keywords comma separated list
  # type: list
  # value: n/a
  # example: 'hdcam', 'camrip',
  bad_index_title_list: [
  ]
  # description: bad imdb movie titles comma separated list
  # type: list
  # value: n/a
  # example: 'star wars', 'star trek',
  bad_movie_title_list: [
  ]
  # description: bad imdb genres comma separated list
  # type: list
  # value: n/a
  # example: 'musical', 'music',
  bad_genre_list: [
  ]
  # description: preferred imdb cast names comma separated list
  # type: list
  # value: n/a
  # example: 'jason statham', 'christian bale',
  override_cast_list: [
  ]
  # description: preferred imdb writer names comma separated list
  # type: list
  # value: n/a
  # example: 'billy wilder', 'robert towne',
  override_writer_list: [
  ]
  # description: preferred imdb director names comma separated list
  # type: list
  # value: n/a
  # example: 'steven spielberg', 'james cameron',
  override_director_list: [
  ]
  # description: preferred imdb movie titles comma separated list
  # type: list
  # value: n/a
  # example: 'star trek', 'transformers',
  override_movie_title_list: [
  ]
  # description: preferred quality releases comma separated list
  # type: list
  # value: n/a
  # example: 'remastered', 'directors cut',
  preferred_index_quality_list: [
  ]
  # description: preferred index groups comma separated list
  # type: list
  # value: n/a
  # example: 'fgt', 'wiki',
  preferred_index_group_list: [
  ]
  # description: preferred imdb characters comma separated list
  # type: list
  # value: n/a
  # example: 'superman', 'jack sparrow',
  override_character_list: [
  ]

torrent_client:
  # description: torrent client to use
  # type: string
  # value: 'qbittorrent|deluge'
  # example: 'qbittorrent'
  selected: 'qbittorrent'
  qbittorrent:
    # description: ip address of torrent client
    # type: string
    # value: n/a
    # example: '192.168.1.100'
    host: ''
    # description: port for web ui of torrent client
    # type: integer
    # value: n/a
    # example: 8080
    port: 8080
    # description: username of torrent client
    # type: string
    # value: n/a
    # example: 'admin'
    username: 'admin'
    # description: password of torrent client
    # type: string
    # value: n/a
    # example: 'adminadmin'
    password: 'adminadmin'
    # description: add torrents paused
    # type: boolean
    # value: True|False
    # example: True
    add_paused: True
    # description: category name e.g. 'movies-siphonator'
    # value: string
    # example:
    category: 'movies-siphonator'

notification:
  email:
    # description: enable email notification of matches
    # value: boolean
    # example:
    enabled: True
    # description: email server hostname e.g. 'smtp.gmail.com'
    # value: string
    # example:
    host: ''
    # description: email server port e.g. 587
    # value: integer
    # example:
    port: 587
    # description: enable email server tls
    # value: boolean
    # example:
    enable_tls: True
    # enable email server ssl
    # value: boolean
    # example:
    enable_ssl: False
    # description: email server username
    # value: string
    # example:
    username: ''
    # description: email server password
    # value: string
    # example:
    password: ''
    # description: email from address
    # value: string
    # example:
    from_address: ''
    # description: email to address
    # value: string
    # example:
    to_address: ''

index_proxy:
  selected: 'jackett'
  jackett:
    # description:
    # type:
    # value:
    # example:
    host: "192.168.1.10"
    # description:
    # type:
    # value:
    # example:
    port: "1900"
    # description:
    # type:
    # value:
    # example:
    api_key: "o4xte43ftp56m64aknxch4pe7cp3lhaj"
    # description:
    # type:
    # value:
    # example:
    read_timeout: 60.0
    # description:
    # type:
    # value:
    # example:
    limit: "2000"

credentials:
  tmdb:
    # description:
    # type:
    # value:
    # example:
    api_key: "1d93addd6def495cec493845cd3b2788"
  omdb:
    # description:
    # type:
    # value:
    # example:
    api_key: "bc61f97e"

index_site:
  # description:
  # type: list
  # value: n/a
  # example: 'showrss',
  ignore_list: [
  ]
  # description:
  # type:
  # value:
  # example:
  search_dict_list: [
    {
      'index_site_search': '1080p',
      'index_site_category': '2000',
      'filter_minimum_size_mb': 3000,
      'filter_maximum_size_mb': 20000,
      'filter_minimum_bitrate_mb': 42,
    },
    {
      'index_site_search': '2160p',
      'index_site_category': '2000',
      'filter_minimum_size_mb': 15000,
      'filter_maximum_size_mb': 30000,
      'filter_minimum_bitrate_mb': 170,
    },
    {
      'index_site_search': '2160p remux',
      'index_site_category': '2000',
      'filter_minimum_size_mb': 30000,
      'filter_maximum_size_mb': 170000,
      'filter_minimum_bitrate_mb': 360,
    },
  ]
